/*
 * IDENTIFICATION:
 * stub generated Wed Sep  7 11:48:19 2016
 * with a MiG generated by bootstrap_cmds-93
 * OPTIONS: 
 *	KernelUser
 */

/* Module sm_report */

#define	__MIG_check__Request__sm_report_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>

#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__sm_report_subsystem__defined
#define __Request__sm_report_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t task;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int32_t do_stacktrace;
		int32_t pid;
		uint64_t tid;
		mach_msg_type_number_t log_fileOffset; /* MiG doesn't use it */
		mach_msg_type_number_t log_fileCnt;
		char log_file[1024];
		mach_msg_type_number_t proc_pathOffset; /* MiG doesn't use it */
		mach_msg_type_number_t proc_pathCnt;
		char proc_path[1024];
		mach_msg_type_number_t reportOffset; /* MiG doesn't use it */
		mach_msg_type_number_t reportCnt;
		char report[2048];
	} __Request__sm_report_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__sm_report_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__sm_report_subsystem__defined
#define __Reply__sm_report_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__sm_report_t __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__sm_report_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__sm_report_subsystem__defined
#define __ReplyUnion__sm_report_subsystem__defined
union __ReplyUnion__sm_report_subsystem {
	__Reply__sm_report_t Reply_sm_report;
};
#endif /* __RequestUnion__sm_report_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _Xsm_report
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__sm_report_subsystem__
#if !defined(__MIG_check__Request__sm_report_t__defined)
#define __MIG_check__Request__sm_report_t__defined

mig_internal kern_return_t __MIG_check__Request__sm_report_t(__attribute__((__unused__)) __Request__sm_report_t *In0P, __attribute__((__unused__)) __Request__sm_report_t **In1PP, __attribute__((__unused__)) __Request__sm_report_t **In2PP)
{

	typedef __Request__sm_report_t __Request;
	__Request *In1P;
	__Request *In2P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->task.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->task.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__sm_report_t__log_fileCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__sm_report_t__log_fileCnt(&In0P->log_fileCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__sm_report_t__log_fileCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->log_fileCnt);
#if	__MigTypeCheck
	if ( In0P->log_fileCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In0P->log_fileCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In0P->log_fileCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 1024);

#if defined(__NDR_convert__int_rep__Request__sm_report_t__proc_pathCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__sm_report_t__proc_pathCnt(&In1P->proc_pathCnt, In1P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__sm_report_t__proc_pathCnt__defined */
	msgh_size_delta = _WALIGN_(In1P->proc_pathCnt);
#if	__MigTypeCheck
	if ( In1P->proc_pathCnt > 1024 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In1P->proc_pathCnt) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In1P->proc_pathCnt)))
		return MIG_BAD_ARGUMENTS;
	msgh_size -= msgh_size_delta;
#endif	/* __MigTypeCheck */

	*In2PP = In2P = (__Request *) ((pointer_t) In1P + msgh_size_delta - 1024);

#if defined(__NDR_convert__int_rep__Request__sm_report_t__reportCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__sm_report_t__reportCnt(&In2P->reportCnt, In2P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__sm_report_t__reportCnt__defined */
#if	__MigTypeCheck
	if ( In2P->reportCnt > 2048 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 4096)) < In2P->reportCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 4096) + _WALIGN_(In2P->reportCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->log_file),  1024);
		if (( memchr(In0P->log_file, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
		memchr_limit = min((msg_limit - In1P->proc_path),  1024);
		if (( memchr(In1P->proc_path, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
		memchr_limit = min((msg_limit - In2P->report),  2048);
		if (( memchr(In2P->report, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__sm_report_t__defined) */
#endif /* __MIG_check__Request__sm_report_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine sm_report */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t sm_report
(
	mach_port_t server_port,
	task_t task,
	int32_t do_stacktrace,
	int32_t pid,
	uint64_t tid,
	sm_filename_t log_file,
	sm_path_t proc_path,
	sm_report_t report
);

/* Routine sm_report */
mig_internal novalue _Xsm_report
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t task;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int32_t do_stacktrace;
		int32_t pid;
		uint64_t tid;
		mach_msg_type_number_t log_fileOffset; /* MiG doesn't use it */
		mach_msg_type_number_t log_fileCnt;
		char log_file[1024];
		mach_msg_type_number_t proc_pathOffset; /* MiG doesn't use it */
		mach_msg_type_number_t proc_pathCnt;
		char proc_path[1024];
		mach_msg_type_number_t reportOffset; /* MiG doesn't use it */
		mach_msg_type_number_t reportCnt;
		char report[2048];
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__sm_report_t __Request;
	typedef __Reply__sm_report_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Request *In2P;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__sm_report_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__sm_report_t__defined */

	__DeclareRcvRpc(666, "sm_report")
	__BeforeRcvRpc(666, "sm_report")

#if	defined(__MIG_check__Request__sm_report_t__defined)
	check_result = __MIG_check__Request__sm_report_t((__Request *)In0P, (__Request **)&In1P, (__Request **)&In2P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__sm_report_t__defined) */

	OutP->RetCode = sm_report(In0P->Head.msgh_request_port, In0P->task.name, In0P->do_stacktrace, In0P->pid, In0P->tid, In0P->log_file, In1P->proc_path, In2P->report);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(666, "sm_report")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t sm_report_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t sm_report_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct sm_report_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[1];
} sm_report_subsystem = {
	sm_report_server_routine,
	666,
	667,
	(mach_msg_size_t)sizeof(union __ReplyUnion__sm_report_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsm_report, 9, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__sm_report_t)},
	}
};

mig_external boolean_t sm_report_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;

	if ((InHeadP->msgh_id > 666) || (InHeadP->msgh_id < 666) ||
	    ((routine = sm_report_subsystem.routine[InHeadP->msgh_id - 666].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t sm_report_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 666;

	if ((msgh_id > 0) || (msgh_id < 0))
		return 0;

	return sm_report_subsystem.routine[msgh_id].stub_routine;
}
